# latest compose version
version: '3.8'

# services (containers)
services:
  server:
  # where is the app (context) to work with
    build: .
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    links:
      - mysqldb
    depends_on:
      - mysqldb
    volumes:
      - .:/home/app

  # MySQL container named as 'mysqldb'
  mysqldb:
    # MySQL image
    image: mysql
    # environment variables from .env file
    env_file:
      - ./.env
    restart: always
    # MySQL configuration
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    # ports - pc_port:internal_docker_port
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: 

# docker-compose up